#!/usr/bin/env bash
# Install and configure Nginx server for redirection

sudo apt-get -y update
sudo apt-get -y install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.facebook.com permanent;' /etc/nginx/sites-available/default
sudo service nginx reload
