#!/usr/bin/env bash
# A Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sigterm_msg="I hate the kill command"
sigint_msg="Y U no love me?!"

trap 'echo $sigterm_msg' SIGTERM
trap 'echo $sigint_msg' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT
trap 'rm /var/run/myscript.pid' SIGTERM

echo $$ > /var/run/myscript.pid

while (true);
do
	echo "To infinity and beyond"
done
