#!/usr/bin/env bash
# init script for manage_my_process

arg="$1"

function start()
{
	./manage_my_process
	"pgrep -f manage_my_process" >> /var/run/my_process.pid
	echo "manage_my_process started"
}

function stop()
{
	pkill -f "manage_my_process"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}

function restart()
{
	pkill -f "manage_my_process"
	rm /var/run/my_process.pid
	./manage_my_process	
	"pgrep -f manage_my_process" >> /var/run/my_process.pid
	echo "manage_my_process restarted"
}

case "$arg"  in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		exit 1
esac
