#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefinitely
# With a sleep 2 in between each iteration
# Displays "I am invincible!!!" when receiving SIGTERM signal

function message()
{
	echo "I am invincible!!!";
}

trap message SIGTERM

while (true);
do
	echo "To infinity and beyond"
	sleep 2
done
