#!/usr/bin/env bash
# A Bash script that loops from 1 to 20.
# displays 4 and then "bad luck from Chine" for the 4th iteration
# displays 9 and then "bad luck from Japan" for the 9th iteration
# displays 17  and then "bad luck from Italy" for the 17th iteration

i=1
while [ "$i" -le 20 ];
do
	if [ "$i" -eq 4 ];
	then
		echo "$i"
		echo "bad luck from China"
	elif [ "$i" -eq 9 ]
	then
		echo "$i"
		echo "bad luck from Japan"
	elif [ "$i" -eq 17 ]
	then
		echo "$i"
		echo "bad luck from Italy"
	else
		echo "$i"
	fi
	((i++))
done
