#!/usr/bin/env bash
# A Bash script that displays the content of the current dir
# in a list format
# where only the part of the name after the first dash is displayed

list=$(ls)
for n in $list;
do
	echo "$n" | cut -d '-' -f2
done
